### ISSUE TITLE
Folder Syntax are not supported

### ISSUE THREAD

**Issue by MattiasEppler** [kzu/GitInfo#101]
We use folder syntax to create release branches.

for example release/v1.3.0

GitInfo does not support this syntax.

**Comment by kzu** [comment]
I guess we could just split by `\` or `/` and consider just the last fragment, right?

**Comment by MattiasEppler** [comment]
Yes that's ok.

**Comment by kzu** [comment]
Sorry it took so long @MattiasEppler !
