### ISSUE TITLE
ASP.NET Core 3.1 GitThisAssemblyMetadata setting?

### ISSUE THREAD

**Issue by Aaron-P** [kzu/GitInfo#108]
I have tried setting GitThisAssemblyMetadata to true using a property group in the project .csproj and Directory.Build.props but the ADDMETADATA doesn't get defined.  I'm not sure how to get this setting to work with .net core.

[TEST.App.csproj.txt](https://github.com/kzu/GitInfo/files/4299300/TEST.App.csproj.txt)

**Comment by joacar** [comment]
Hi @Aaron-P 
Have the same issue. Setting the `ADDMETADATA` as Conditional compilations symbols (Right click csproj > Properties > Build) explicitly works. Then you can get them 

```c#
var gitAttributes = typeof(Startup).Assembly.GetCustomAttributes(typeof(System.Reflection.AssemblyMetadataAttribute));
```

**Comment by Aaron-P** [comment]
I manually add the symbol for now, but this question would still matter for the other options that you can set.
