### ISSUE TITLE
Use MSBuild property to determine base version instead of external file

### ISSUE THREAD

**Issue by mgnslndh** [kzu/GitInfo#113]
Is it possible to use an MSBuild property to determine base version instead of tag/branch or external file?

This seems to indicate that it is possible to set the $(GitBaseVersion) from MSBuild:
https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L78

I can't get it to work. Is it possible? When/Where should the variable be assigned?

**Comment by summer600** [comment]
Not sure whether my issue is like this. But i wanted to get the GitSha into minver as described in https://rehansaeed.com/the-easiest-way-to-version-nuget-packages/ and tried minver myself with gitinfo (which @rehan did not mention without success as mentioned in https://github.com/adamralph/minver/issues/334

**Comment by kzu** [comment]
The behavior you're looking for is triggered when you set `GitDefaultVersion`, which is used in [the default fallback](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L769) if no other base version is determined. That other line is confusing, will remove it :)
