### ISSUE TITLE
Add GitSha override when building

### ISSUE THREAD

**Issue by yunj** [kzu/GitInfo#114]
`GitInfo.targets` has several properties which can be overridden from command line when running MSBUILD, for example, `GitCommits`. I am wondering if it's feasible to override `GitSha`, the full version of commit? Our test does not care about the value of SHA as long as it is valid. Thanks.
```
</PropertyGroup>
  <!-- Defaults if overrides are specified when building -->
  <GitCommits Condition="'$(GitCommits)' == ''">0</GitCommits>
</PropertyGroup>
```

**Comment by kzu** [comment]
You can [already do that](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L71). Just provide a `GitDefaultCommit` or even an entirely made-up `GitCommit` and [the target that calculates it won't even run](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L440).

For example, just set this on your project:

```xml
<Project>
   <ProjectGroup>
      <GitCommit>asdfasdf</GitCommit>
```

HTH
