### ISSUE TITLE
Possibility to exclude tag refs from $(GitBranch)

### ISSUE THREAD

**Issue by andersforsgren** [kzu/GitInfo#126]
We reference the branch name from `$(GitBranch)` in msbuild and also in C#, in order to e.g. display it in the app, determine where to deploy and so on. This works great - unless the commit also has a tag. Since our build system tags the build number on the commit, this gives a weird effect. 

Example: I build commit abcabc on master. The application about box displays "abcabc (master)". If I build the same commit again, it now has a tag, and that tag name is now returned as $(GitBranch)! The result is that the about box shows "abcabc (build-12345)", which is not what I'd expect.

The code responsible for this is in [GitInfo.targets](https://github.com/kzu/GitInfo/blob/30a6d142d691363fad9056a005a58fa7080d9636/src/GitInfo/build/GitInfo.targets#L426) where it does

```xml
<Exec Command='$(GitExe) name-rev --name-only HEAD'
``` 

The alternative that does what I want is for example this:

``` 
git name-rev --refs=refs/heads/* --name-only HEAD
```

I'd be happy to provide a PR for this, but unsure how this would be configured, e.g. if it would be a new option. Options for that include e.g. (Ignore the naming): `$(IgnoreTagsForGitBranch)=true/false`, or a more powerful general one that allows include/exclude, e.g.  `$(GitNameRevOptions)=--refs=refs/heads --refs=refs/tags`, in which case the Exec would just pass them along

```
   <Exec Command='$(GitExe) name-rev --name-only $(GitNameRevOptions) HEAD'
```

**Comment by kzu** [comment]
I can't think of a scenario where having the tag as the branch makes sense actually. I would actually make the condition the opposite: `IncludeTagsForGitBranch` to turn on the (new) legacy behavior. 

Then you'd do `GitNameRevOptions=--refs=refs/heads` by default, unless the "legacy" behavior is `true`. I'd still introduce the `GitNameRevOptions` property as an advanced escape hatch for future proofing.

**Comment by andersforsgren** [comment]
Perhaps it’s easiest to use a single new $(GitRevNameOptions) and its default value unless ocerridden would be to include refs/heads/*? 

So everyone would see the new behavior, but could set the property to something like `—refs=*` to get the legacy behavior.

**Comment by kzu** [comment]
Yes, that makes sense!

**Comment by andersforsgren** [comment]
Cool. I'll try to cook up a PR.
