### ISSUE TITLE
Error when the path to file GitInfo.txt contains spaces

### ISSUE THREAD

**Issue by timrou** [kzu/GitInfo#13]
Missing quotes in GitInfo.targets line 370.
$(GitExe) rev-list --count "$(_GitLastBump)"..HEAD $([System.IO.Path]::GetDirectoryName("$(GitVersionFile)")) 
should be
$(GitExe) rev-list --count "$(_GitLastBump)"..HEAD **"**$([System.IO.Path]::GetDirectoryName("$(GitVersionFile)"))**"**

Caused this error:
C:\Program Files (x86)\Jenkins\workspace\develop\packages\GitInfo.1.1.31\build\GitInfo.targets(370,3): warning MSB3073: The command ""C:\Program Files\Git\bin\git.exe" rev-list --count "65923a7"..HEAD C:\Program Files (x86)\Jenkins\workspace\develop" exited with code 128. [C:\Program Files (x86)\Jenkins\workspace\develop\project.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  Build continuing because "ContinueOnError" on the task "Exec" is set to "true".
C:\Program Files (x86)\Jenkins\workspace\develop\packages\GitInfo.1.1.31\build\GitInfo.targets(586,4): error MSB4186: Invalid static method invocation syntax: "[MSBuild]::Add('$(GitBaseVersionPatch)', '$(GitCommits)')". Input string was not in a correct format. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).  [C:\Program Files (x86)\Jenkins\workspace\develop\project.csproj]

It worked after adding the quotes manually -.-

**Comment by kzu** [comment]
Care to send a PR so you get proper credit?
