### ISSUE TITLE
Parent library version mismatch within same solution

### ISSUE THREAD

**Issue by Noggog** [kzu/GitInfo#134]
Hey Kzu!  Thanks for the amazing tool.  I'm having some odd results that I believe will end up being improper target definitions, but I'm not sure.  I have a solution with several projects.  There's several projects that depend on another project within this same solution.    I have a custom target that is setting my assembly versions that I stuck in my Directory.Build.Props:
```
 <Target Name="SetVersion" AfterTargets="GitVersion" BeforeTargets="GetPackageVersion;GitThisAssembly" Condition="'$(ExcludeRestorePackageImports)' != 'true'">
    <PropertyGroup>
      <DevLabel Condition="'$(GitCommits)' != '0' or $(GitIsDirty) == 'true'">.1-dev</DevLabel>
      <AssemblyDevLabel Condition="'$(GitCommits)' != '0' or $(GitIsDirty) == 'true'">.1</AssemblyDevLabel>
      <AssemblyVersion>$(GitBaseVersionMajor).$(GitBaseVersionMinor).$(GitBaseVersionPatch)$(AssemblyDevLabel)</AssemblyVersion>
      <FileVersion>$(GitBaseVersionMajor).$(GitBaseVersionMinor).$(GitBaseVersionPatch)$(AssemblyDevLabel)</FileVersion>
      <PackageVersion>$(GitBaseVersionMajor).$(GitBaseVersionMinor).$(GitBaseVersionPatch)$(DevLabel)</PackageVersion>
      <InformationalVersion>$(PackageVersion)</InformationalVersion>
    </PropertyGroup>
  </Target>
```
Pretty similar to other targets people have posted in other issues.   It sets my assembly version, and my nuget package version just fine.  I have my project to automatically build nuget packages and everything seems to line up... except:

I've noticed that each nuget/assembly gets the proper version stamps, but within each nuget, the version numbers of their parent packages is not set.  For example:

```
My Solution/
   My Project A/
   My Project B/    <--- Depends on A
```
If I build, I might get a version 0.1.2.3 stamped on A and B's assemblies, and resulting nuget packages.  However, B's nuget package will list that it depends on v1.0.0.0 of A.  I interpret this as that it wasn't set, and defaulted to v1?  Something in the pipeline isn't being set at the right time?

Is there something wrong with my targets, or something at play that you're aware of to cause the missing parent dependency version numbers being set?  I'm super excited to let GitInfo drive everything, but this is one last hurdle to letting it run wild for me.   Thanks in advance!

**Comment by Noggog** [comment]
Just to provide some supplemental examples to help communicate what I'm seeing, I've uploaded a small repo showing a minimalistic example:
https://github.com/Noggog/GitInfoTests

This just has two libraries using GitInfo, one is a parent of the other, and the repo has a single tag (0.5.5).

The nuget packages being built by it show the problem I'm dealing with, namely that the child nuget package lists needing the parent nuget v1.0.0, even though the whole rest of the setup is stamped with 0.5.5

![GitInfoExample](https://user-images.githubusercontent.com/24981326/95693324-a2646380-0be0-11eb-82b1-afa891eda965.png)

**Comment by kzu** [comment]
I see you're not using https://github.com/kzu/nugetizer, so that means the `BeforeTargets="GetPackageVersion"` isn't really doing anything (since that's a nugetizer target). The target to add there for the SDK Pack you're using is `GenerateNuspec` 😉 .

Let me know if that fixes the issue!

**Comment by Noggog** [comment]
Hey kzu!  Thanks very much for the suggestion.   I swapped out `GetPackageVersion` for `GenerateNuspec` and it seemed to get similar improper results.  

However, I'm now seeing where the resulting `.nuspec` within the nuget package has the improper 1.0 marking.  Digging further, I can see within my project's `obj/` folter is `project.assets.json` which seems to list the improper version within, both for the current library as well as the parent. 
![image](https://user-images.githubusercontent.com/24981326/96208662-e5953e00-0f22-11eb-849e-980d1283d168.png)

So maybe I need to get an even earlier target that comes before project.assets.json is generated?

And damn, you really gone rapid fire development on nugetizer the past bit.  I'll dig in sometime soon to see what's what.  At first glance I'm not gathering a quick 101 on how I'd substitute it in place of the existing packing mechanisms.  But I'm not too knowledgeable on build processes internals.

**Comment by kzu** [comment]
Not sure what changed, but the built-in SDK pack is so confusing and unnecessarily tied to restore that it's nearly impossible to extend in meaningful ways. In your case, for example, since the graph is generated on restore and that's what determines the version in that json file, GitInfo might not have been restored yet (in fact, during restore it will *not* be imported, even if it was restored before), so you have none of the targets in it available to customize the version. Catch-22, really.

NuGetizer suffers from none of those issues, because it's based on an explicit targets-based protocol across projects that kicks-in at Pack time. Each project can express what they contribute to a package, via the GetPackageContents target and the referencing project gets to consume it that way. 

I just added nugetizer to your sample project and voila, things Just Work: https://github.com/Noggog/GitInfoTests/pull/1

**Comment by kzu** [comment]
Also, since the issue is beyond gitinfo itself, I'm tentatively going to close this, but I'll keep an eye for your thoughts on this.

Thanks!

**Comment by Noggog** [comment]
Thanks so much for the PR!  I tried it out, and indeed, the package looks properly stamped as intended.

I'll pick up any other issues I have elsewhere.   I'll leave the repository up for posterity for others. 8)
