### ISSUE TITLE
How to use GitInfo from Directory.Build.props at the root of the git repository? 

### ISSUE THREAD

**Issue by noamyogev84** [kzu/GitInfo#136]
Hi,
How can I use GitInfo from Directory.Build.props at the root of the git repository?

**Comment by noamyogev84** [comment]
I'm trying to version all my dll's under the root folder, using Directory.build.props and add commit hash as revision number.
How can I achieve that with this library?

**Comment by kzu** [comment]
Did you look at the provided examples? They all do what you are looking for. 

Please reopen if you have a more specific doubt. What you're trying to do requires knowledge of MSBuild, and those examples show how that's done.

Thanks
