### ISSUE TITLE
Patch version is not correct

### ISSUE THREAD

**Issue by IAfanasov** [kzu/GitInfo#15]
I have a solution and last hotfix is 2.119.16. GitInfo thinks that current version is 2.119.14. Where is tag and merge commint for hotfix/2.119.16. How can I find a reason of this calculation mistake?

**Comment by kzu** [comment]
run a detailed build and you'll see all the information that's being calculated by GitInfo and other targets.

To make the output less verbose, you can just run the GitVersion target, as follows:

    msbuild [myproject] /t:GitVersion /v:detailed

I strongly suggest you try out the [MSBuild Structured Logger](https://github.com/KirillOsenkov/MSBuildStructuredLog) to have a clearer view than a looong log output. You can pass the exact same parameters as above to the tool and it will yield a very nice and even searchable tree of the process.

![structuredgitinfo](https://cloud.githubusercontent.com/assets/169707/19562326/3f98f3c6-96b2-11e6-936e-54c8a41aca5a.PNG)

**Comment by kzu** [comment]
Closing as we got no further info to diagnose.

Please reopen if you follow the suggested steps and you still see weird behavior.

Thanks
