### ISSUE TITLE
Build error with 1.1.32

### ISSUE THREAD

**Issue by davidjade** [kzu/GitInfo#17]
Commit 3ff0168c5d504835883df91fdce6b1f46fe655cf has broken my project, which does use XAML (a WPF project). Prior to this change it was building fine. After this change I get the following build error when using VS 2015 update 3:

obj\Debug\ThisAssembly.GitInfo.g.cs" was specified more than once in the "Sources" parameter

**Comment by kzu** [comment]
Could you provide a diagnostic build log?

**Comment by davidjade** [comment]
Sure, do you have a place that is non-public for me to send it to you?

**Comment by kzu** [comment]
You can just create a private gist I guess? Send to daniel at cazzulino dot com
