### ISSUE TITLE
Would be super swell to get GitInfo to work with Nugetizer packaging projects.

### ISSUE THREAD

**Issue by bbowman** [kzu/GitInfo#18]
It appears right now GitInfo make some assumptions about the language of the project for assembly inspection. It would be nice if this was factored out and at least the straight git integration could work by default regardless of language. As is, $(GitThisAssembly) needs manually turned on which is a bit unfortunate.

**Comment by kzu** [comment]
Not sure I follow. GitInfo supports ThisAssembly generation in a couple of languages, namely, C# and VB. It can surely be extended to support more. You just need to send a PR with the right `.pp` file (see https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.cs.pp) and add that newly supported language to the condition at https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L60.

Without the .pp file with the source, tweaking the `GitThisAssembly` won't magically give you source in a new language ;)

**Comment by kzu** [comment]
Also, what would be the purpose/use of the ThisAssembly static class in C# in a project that has no language or source code? (like nugetizer packaging projects?)

**Comment by bbowman** [comment]
Ah the confusion is a bit around the purpose of the GitInfo package to begin with. You are making the contention that its primary purpose is to generate assembly version information with git.exe.

My contention is that its usefulness is two-fold:
1. inject useful git information into MsBuild.
2. Generate Assembly information based on git.

The former should work without having to manually tell it to $(GitThisAssembly) and would be useful for a .nuproj because as you say the actual assembly information bit wont be super useful in a .nuproj.

My final vision is:
1. GitInfo on a .nuproj allows the user to customize the package version with useful git properties (GitSemVer or similar msbuild variables) and
2. The assemblies inside that package are similarly versioned (which I still intend to eventually send a PR for native support as we currently do this manually).

Does that make more sense?

**Comment by bbowman** [comment]
I'll get back to you on this. I was seeing that I needed to set $(GitThisAssembly) to true in my project to get the basics. Its possible I was just misunderstanding what was going on and had a mismatch of target orders or something.

**Comment by kzu** [comment]
Closing, since this is quite old and possibly already resolved?
