### ISSUE TITLE
Confused about where values come from

### ISSUE THREAD

**Issue by asherber** [kzu/GitInfo#21]
Getting my feet wet with this package, and I'm confused about where things are coming from. I have a project that looks like this:

![image](https://cloud.githubusercontent.com/assets/5248041/21474384/62da48e4-caec-11e6-9444-2f622f03ab51.png)

When I build this with no GitInfo.txt and no customization, I get:
```
GitBranch=master;
GitCommit=8860bcb;
GitSha=8860bcb59f1e83db93e6aea90d1e8928bb1e692f;
GitBaseVersion=0.1.0;
GitBaseVersionSource=;
GitBaseVersionMajor=0;
GitBaseVersionMinor=1;
GitBaseVersionPatch=0;
GitCommits=0;
GitTag=v2.1-1-g8860bcb;
GitBaseTag=v2.1;
GitSemVerMajor=0;
GitSemVerMinor=1;
GitSemVerPatch=0;
GitSemVerLabel=;
GitSemVerDashLabel=;
GitSemVerSource=Default
```
GitInfo sees the tag, so why is it using the default 0.1.0 as the BaseVersion and SemVer?

Shouldn't GitCommits be 1, since I'm 1 commit ahead of the tag?

Thanks for any clarification.

**Comment by kzu** [comment]
The tag version is not a valid semver, which is why it isn't used. It should be v2.1.0. 

A detailed build log would show that, IIRC

**Comment by asherber** [comment]
Thanks. I did look at a detailed build log, but I must have missed it.
