### ISSUE TITLE
Branch names with slashes are chopped

### ISSUE THREAD

**Issue by ermau** [kzu/GitInfo#27]
If you have a branch name of `ermau/feature`, GitInfo will read the branch name as `feature` only.

```
$ git name-rev --name-only HEAD
ermau/feature
```

**Comment by jdesmedt** [comment]
I also have this issue... Very annoying since we use release/0.0.1 to create release candidates. Because of this issue, we have no way to get the full branchname and thus determine if we should build an RC...

**Comment by kzu** [comment]
Just a reminder that a little bit of MSBuild can get you a long way: https://github.com/kzu/GitInfo/issues/95#issuecomment-542349622
