### ISSUE TITLE
VB.Net: Strict Mode

### ISSUE THREAD

**Issue by wahmedswl** [kzu/GitInfo#32]
Hi, ```BC30209	Option Strict On requires all variable declarations to have an 'As' clause.``` is causing build to fail.

Any help would be appreciated, Thanks

**Comment by kzu** [comment]
Here's the VB template file: https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.vb.pp

Care to open a PR?

Thanks!

(also, FWIW, you can modify it locally from the package you referenced, until you make it work for you, then send the PR)
