### ISSUE TITLE
ThisAssembly.Git.Commit: Information Mis-match

### ISSUE THREAD

**Issue by wahmedswl** [kzu/GitInfo#33]
Hi, i started to use GitInfo for versioning and while checking generated version detail, seems like something is wrong

```AssemblyInfo```

![vs-assemblyinfo](https://cloud.githubusercontent.com/assets/15020561/25250243/40714044-262e-11e7-969e-aeed4eb31057.PNG)

```Git History```

![vs-githistory](https://cloud.githubusercontent.com/assets/15020561/25250279/62928908-262e-11e7-8a7f-9578267a5f30.PNG)

```Application Detail```

![application-detail](https://cloud.githubusercontent.com/assets/15020561/25250239/3b0740d6-262e-11e7-8f78-2dab4f0e9cb7.PNG)

Any help would be appreciated, Thanks

**Comment by wahmedswl** [comment]
Hi, following is the build output related to GitInfo

```
_GitRoot:                                                                                                               
  "C:\Program Files\Git\bin\git.exe" rev-parse --show-toplevel                                                          
  The command ""C:\Program Files\Git\bin\git.exe" diff-index --quiet HEAD" exited with code 1.                          
_GitClearCache:                                                                                                         
  Deleting file "obj\x86\Release\GitInfo.cache".                                                                        
_GitCommit:                                                                                                             
  "C:\Program Files\Git\bin\git.exe" log --format=format:%%h -n 1                                                       
  "C:\Program Files\Git\bin\git.exe" log --format=format:%%H -n 1                                                       
_GitBaseVersionTagExists:                                                                                               
  "C:\Program Files\Git\bin\git.exe" describe --tags --abbrev=0                                                         
  The command ""C:\Program Files\Git\bin\git.exe" describe --tags --abbrev=0" exited with code 128.                     
_GitBaseVersionFile:                                                                                                    
  Using base version from version file E:\Development\Production-WS\Lab\GitInfo.txt'                                    
  "C:\Program Files\Git\bin\git.exe" log -n 1 --format=format:%%h "E:\Development\Production-WS\Lab\GitInfo.txt"        
  "C:\Program Files\Git\bin\git.exe" rev-list --count --full-history "9d10c23"..HEAD "E:\Development\Production-WS\Lab" 
```

**Comment by kzu** [comment]
Without knowing the contents of the `GitInfo.txt` file, it's impossible to know if the version is correct or not.

Also, when a file is used, the commits from that file directory are used for commit count. From your  screenshot, it looks like the commit hash is the right one, so I'm not sure what the problem is?

Note: `git.exe rev-list --count --full-history "9d10c23"..HEAD`. Looks like `9d10c23` was the commit that last touched `GitInfo.txt`. But again, without knowing what its contents are, hard to know. 

I'd guess you have 1.0.0 on it, created on `9d10c23`, then added 3 more commits on top, and that's why you're getting 1.0.3. The trailing `.0` on the file version is because tools that expect 4 segment Version will default it to zero. Not sure that you used to take that screenshot. 

But it seems to work as expected, TBH.

**Comment by wahmedswl** [comment]
Sorry, i just missed to mention the issue, ```ThisAssembly.Git.Commit``` returned ```39c3ee6``` but it should be ```39c3ee68```.

**Comment by kzu** [comment]
> it defaults to using seven characters

https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1

That's why you see 7 chars there. You can actually see for yourself by running the build with diagnostics and observing the git commands issued by GitInfo, and then running them yourself in the command line.

**Comment by wahmedswl** [comment]
Sorry, i am commenting on the close ticket but it seems like tools are using 7-8 chars and guide also suggests ```Generally, eight to ten characters are more than enough to be unique within a project```.

GitHub using 7 chars 

![image](https://cloud.githubusercontent.com/assets/15020561/25354660/489a197c-294d-11e7-9fc6-440096098398.png)

GitLab using 8 chars

![image](https://cloud.githubusercontent.com/assets/15020561/25354697/7052566e-294d-11e7-97f5-895091b3fb17.png)

There should be way to configure this as this was the exact reason due to which i created this ticket because SHA i was seeing in VS and GitLab was different from the Version.

Thanks so much for your reference
