### ISSUE TITLE
Build fails from dotnet publish

### ISSUE THREAD

**Issue by KuroThing** [kzu/GitInfo#41]
When using dotnet publish to build a .Net Core library (.Net Standard 1.3) while GitInfo is referenced, the build will fail due to attempting to download MSBuild via nuget, which exits with code 1.

It appears somewhere in the command `nuget install MSBuild -outputdirectory "%user%\.nuget\packages\gitinfo\1.1.62\build\..\..\" -excludeversion -source "https://www.nuget.com/api/v2"` there is something wrong that causes a "Illegal characters in path." problem.

If i had to guess whats going on, it would be that you've accidentally escaped a quote on [Line 32 of GitInfo.xbuild](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.xbuild#L36) but then that brings the question of, why does it resort to trying to use the xbuild target (Presumably Due to [`'$(MSBuildRuntimeVersion)' == ''`](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L854)) when using the dotnet cli to publish a project?

I had a quick test of trying to remove the final `\` to unescape the quote and the build went forward to using mono... Which isn't installed since i'm on a Windows system.

**Comment by bojanrajkovic** [comment]
I'm hitting the same issue trying to even get the target to run w/ a .NET Core project.

**Comment by bojanrajkovic** [comment]
OK, made some progress--the target runs if you use `msbuild /t:Pack`, but then the MSBuild variables it's supposed to set are all just empty. Seems like it's something about the ordering of the targets, but I'm not sure what.

**Comment by adamhathcock** [comment]
Will this fix make it work with .NET Core projects?  If so, I'd love it.

**Comment by bojanrajkovic** [comment]
Yep, it should fix all things .NET Core!
