### ISSUE TITLE
Using GitInfo in a WPF app causes build failure

### ISSUE THREAD

**Issue by bojanrajkovic** [kzu/GitInfo#44]
Installing GitInfo in a WPF app causes the build to fail, with the error message that `ThisAssembly.GitInfo.g.cs` was specified more than once in the `Sources` parameter to the `Csc` task.

Running using the MSBuild Structured Log Viewer confirms that the value is indeed in there twice! What appears to be happening is that the project generated by MSBuild for compilation of the solution already has the file (because it's been added to the outer compilation), but then the target is re-run and the file is added *again* to the inner compilation.

You can see this in the attached build log (using Structured Log Viewer's binary format)--I'm using version 1.1.66, installed from NuGet about...30 minutes ago. The project is open source--the branch to look at is https://github.com/bojanrajkovic/Reedy/tree/gitinfo.

[Reedy Broken Build.zip](https://github.com/kzu/GitInfo/files/1117608/Reedy.Broken.Build.zip)

**Comment by kzu** [comment]
Yeah, it sucks. Any ideas on how to avoid it though? I could only come up with de-duplication before compile, or detecting that @(Compile) contains the .g.cs file. Neither of which is quite satisfactory :(.

Maybe I could remove before adding to Compile?

**Comment by bojanrajkovic** [comment]
Remove before adding to Compile seems like a reasonable approach--it's not perfect, but it's more straightforward than either of the other approaches IMO.

**Comment by kzu** [comment]
Should be fixed in 1.1.67
