### ISSUE TITLE
HOWTO dotnet core nuget versioning

### ISSUE THREAD

**Issue by Boggin** [kzu/GitInfo#45]
GitInfo is correctly versioning our assemblies but I would like to extend this to versioning our nuget packages. The following is a snippet from our .csproj :
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageVersion>$(GitSemVerMajor).$(GitSemVerMinor).$(GitSemVerPatch)$(GitSemVerDashLabel)</PackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\GlobalAssemblyInfo.cs" Link="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="gitinfo" Version="1.1.66" />
  </ItemGroup>
</Project>
```
Note the `GeneratePackageOnBuild`.

What do I have to do to generate those environment variables, `$(GitSemVerMajor)`, _etc_. when I call `dotnet build`?

**Comment by kzu** [comment]
Those are not environment variables, they are MSBuild variables determined during the build. Here's [one way to do it](https://github.com/moq/moq/blob/master/src/Version.targets#L11).

The `PackageVersion` property has to be set from within a target that depends on `GitVersion`, which is when everything has been populated. You can achieve that by adding it as an InitialTargets:

```
<Project Sdk="Microsoft.NET.Sdk" InitialTargets="SetVersion">
...
```

**Comment by feliwir** [comment]
The link is dead. Can you please provide a fresh minimal example?

**Comment by Boggin** [comment]
The link refers to the Version.targets in the moq project build: https://github.com/moq/moq/blob/master/src/build/Version.targets

**Comment by kzu** [comment]
@feliwir the key is that you cannot assign those properties *statically* in a `PropertyGroup`, but must do so inside a *Target* that runs *after* `GitInfo` target runs
