### ISSUE TITLE
Cannot access internal class "ThisAssembly" here

### ISSUE THREAD

**Issue by RobSmyth** [kzu/GitInfo#55]
Hi,

Resharper raises errors "Cannot access internal class 'ThisAssembly' here" for each reference to ThisAssembly in the AssemblyInfoExt.cs file. The project does compile and run so it evidently does work.

I toss up as to if this is a Resharper issue or something GitInfo can fix. Anybody else seeing this?

**Comment by MaikuMori** [comment]
Having same issue. It used to work before, no idea what caused it to break.

**Comment by kzu** [comment]
If you could figure out what version it broke on, maybe we can track what's different?

**Comment by MaikuMori** [comment]
It probably broke on some version of Rider, not GitInfo. I'm using the nightly build. I'll try to experiment with some GitInfo versions.

**Comment by RobSmyth** [comment]
It seems (not sure) to happen when I have multiple projects using GitInfo in the one solution and one project referencing the other.

**Comment by MaikuMori** [comment]
My project setup is something like:
 - Main solution
   - App 1 (uses GitInfo, missing assembly in Rider)
   - App 2 (doesn't use GitInfo)

**Comment by RobSmyth** [comment]
Another scenario were I've hit this issue ... I have a production code assembly and a matching unit tests code assembly. I use the attribute `InternalsVisibleTo ` in the production code assembly so that the unit tests can access the internal types. Both assemblies use GitInfo. Once I add this attribute my build breaks due to "Cannot access internal class 'ThisAssembly' here" error.

Note: It is possible that if your not using Resharper or you do not have 'treat warnings as errors' etc, you  may not see this error.

**Comment by MaikuMori** [comment]
I'm working on some components in Windows VM and I have the same problem so this is not platform specific issue. I still think it's really issue in Resharper/Rider than in this project,

**Comment by kzu** [comment]
@RobSmyth that's sort of expected. You should remove GitInfo from test projects, there's no need for it there.

**Comment by RobSmyth** [comment]
Hi, thanks. Yes that is a work around I've gone with.

But to pick you up on:

> "there's no need for it"

 ... true to say that the vast majority of times there is much **_less_** need and it could be removed from the test code assembly. Almost always an acceptable limitations (and one that is OK with me). But, if your shipping the test assembly then that is not true.

Thanks,

Rob

**Comment by kzu** [comment]
> But, if your shipping the test assembly then that is not true.

Yes, it's still true. Just give the test assembly `InternalsVisibleTo` visibility and you can use the referenced project's `ThisAssembly` in the test project's `AssemblyInfo.cs` as usual.

**Comment by RobSmyth** [comment]
Ah! Now that is useful as I think it is good for the test assembly (unit tests) to use the production assembly's assembly info. Nice, I think I'll use that.

To take that a step further ... how about I have one version assembly in the solution and all others get their version from that? Will that cause unnecessary extra recompiles?

Thanks.

**Comment by kzu** [comment]
Sure thing. Check out https://github.com/MobileEssentials/Merq/blob/master/src/GlobalAssemblyInfo.cs and how it's used in the various projects. Basically everything imports https://github.com/MobileEssentials/Merq/blob/master/src/Merq.targets

**Comment by kzu** [comment]
I guess this can be closed @RobSmyth? Not sure there's much GitInfo can do?

**Comment by RobSmyth** [comment]
I agree

**Comment by MaikuMori** [comment]
Just to give heads up for people interested, I reached out to JetBrains and they confirmed and reproduced the problem. Now all we have to do is wait.

**Comment by kevin-osborne** [comment]
works ok in rider 2018.2.3
