### ISSUE TITLE
GitExe in the PATH should be first

### ISSUE THREAD

**Issue by xmedeko** [kzu/GitInfo#6]
When I have the `git.exe` in the PATH, it should take the precedence over other search paths.

**Comment by xmedeko** [comment]
Do not know the MSBuild well, but may the git on the PATH be examined first by the ``Exec IgnoreExitCode=True`` task? Something like ``git --version`` and when it returns the ``ExitCode`` zero then use the git on the PATH.

**Comment by kzu** [comment]
Yes, that should be possible. Would love to get a PR ;)
