### ISSUE TITLE
csproj example

### ISSUE THREAD

**Issue by piccaso** [kzu/GitInfo#62]
Can someone please share a working .csproj example?  
Or tell me wrong what is wrong with mine:
```xml
<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="GitVersion">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;net40</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <version>$(GitTag)</version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GitInfo" Version="2.0.8" PrivateAssets="all" />
  </ItemGroup>
</Project>
```

Thanks!

**Comment by bvli** [comment]
I have this in my `./src/Directory.Build.props`:
```xml
  <ItemGroup>
    <PackageReference Include="gitinfo" Version="2.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <GitInfoReportImportance Condition="$(Configuration) == 'Release'">high</GitInfoReportImportance>
  </PropertyGroup>

  <Target Name="Configure" AfterTargets="GitInfoReport">
    <PropertyGroup>
      <Version>$(GitSemVerMajor).$(GitSemVerMinor).$(GitSemVerPatch)$(GitSemVerDashLabel)</Version>
    </PropertyGroup>
  </Target>
```
It works quite well.

/B :)

**Comment by kzu** [comment]
Here's a couple more: 

https://github.com/clariuslabs/clide/blob/dev/src/Version.targets
https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Directory.Build.targets
https://github.com/MobileEssentials/Merq/blob/master/src/Merq.targets

**Comment by kzu** [comment]
The `Git*` properties are populated when the `GitInfo` target runs (and the version ones when `GitVersion` runs). 

You can't reference those properties before those targets have run. The updated docs on MSBuild go into quite a bit more details on how properties/items/targets are evaluated and run and when. It might be worth checking those out, they are quite well written, I'd say: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties
