### ISSUE TITLE
Default protection level of ThisAssembly

### ISSUE THREAD

**Issue by markfinal** [kzu/GitInfo#69]
Hi,

First of all, great idea for a NuGet package. Wish I'd found it sooner.

Unfortunately, in trying to use ThisAssembly directly as per the readme.txt, i.e. I added this to my C# source:

```
[assembly: AssemblyVersion (ThisAssembly.Git.SemVer.Major + "." + ThisAssembly.Git.SemVer.Minor + "." + ThisAssembly.Git.SemVer.Patch)]
[assembly: AssemblyInformationalVersion (
  ThisAssembly.Git.SemVer.Major + "." +
  ThisAssembly.Git.SemVer.Minor + "." +
  ThisAssembly.Git.SemVer.Patch + "-" +
  ThisAssembly.Git.Branch + "+" +
  ThisAssembly.Git.Commit)]
```

I get this error:

`ThisAssembly' is inaccessible due to its protection level`

since it's declared as

```
  /// <summary>Provides access to the current assembly information.</summary>
  partial class ThisAssembly
  {
```

hence private.

Should ThisAssembly not be public in order to use as advertised?

Observed in both VisualStudio 2013, and VisualStudio for Mac 7.5.2.

Thanks

**Comment by markfinal** [comment]
To further clarify, this error appears on projects of type ClassLibrary. Not ConsoleApplication.

**Comment by markfinal** [comment]
Argh, user error. Sorry.

I have a multi-project solution, each referencing some shared C# code for the assembly info, which I had put a reference to ThisAssembly.

What I hadn't done is add a NuGet package to each and every project that used that reference.
Everything is working as expected.

**Comment by kzu** [comment]
Glad it's working @markfinal! If you switch to the awesome `PackageReference` format for nuget references, you would only need to add it to the top-level dependency, since the reference flows transitively to all referencing projects now :)
