### ISSUE TITLE
Cant get it to work on Universal Windows Platform

### ISSUE THREAD

**Issue by fabiopand** [kzu/GitInfo#7]
I installed v1.1.20 of the package on Desktop, Android, and iOS projects successfully, but for some reason it does not work on UWP.

![issue](https://cloud.githubusercontent.com/assets/9537294/16138845/1a3de52a-3418-11e6-8015-98e91fb1a054.jpg)

**Comment by kzu** [comment]
Close/reopen solution doesn't fix it? Can you still reference the members
and compile, even if intellisense doesn't show them?

**Comment by kzu** [comment]
I've made some changes recently to improve compatibility with more project types at the MSBuild level. 

Is this still failing for you?

PS: it's great you're playing with the FormsPlayer! 👍

**Comment by kzu** [comment]
Closing since we didn't get any more info on the issue.

Please do reopen if it still happens with the latest version.

Thanks!
