### ISSUE TITLE
How to add pre-release information only if building from dev branches or on dev box

### ISSUE THREAD

**Issue by RobSmyth** [kzu/GitInfo#70]
Hi,

I want to use a release SemVer formats when the build is on the build system and in a release branch and a pre-release format in all other cases. How can I do this?

The formats I want are:

```
<Major>.<Minor>.<Path>+<meta>
<Major>.<Minor>.<Path>-Beta+<meta>

```
I can determine if a release msbuild csproj by checking branch name and an environent variable the build system sets. How can I apply this to the generated AssemblyInfo informational version.

**Comment by kzu** [comment]
Here are a few examples:

https://github.com/moq/moq/blob/master/src/build/Version.targets
https://github.com/MobileEssentials/Merq/blob/master/src/Merq.targets#L18-L38
https://github.com/xamarin/Xamarin.VSSDK/blob/master/src/Version.targets#L37

**Comment by kzu** [comment]
Closing since this can be achieved through plain MSBuild
