### ISSUE TITLE
Question regarding ThisAssembly.Git.Tag - separate commit using a plus?

### ISSUE THREAD

**Issue by dueringa** [kzu/GitInfo#78]
ThisAssembly.Git.Tag is currently in the following form, e.g.:

`public const string Tag = "v1.2.3-beta4-5-g6789abcd";`

However, SemVer states that build metadata should be added via a plus sign, so this would be correct

`public const string Tag = "v1.2.3-beta4-5+g6789abcd";`

I'm not sure if this field is actually be specified to be a semantic version. So should this be changed or is this intended?

**Comment by kzu** [comment]
GitInfo does not force anything on you. If you're happy with that format, you can continue using it. You control precisely everything. That is *your * tag, after all

**Comment by dueringa** [comment]
Sorry, my bad, looked at the code again and saw that it results from the output for `git describe --tags`.
