### ISSUE TITLE
gitinfo.txt: ThisAssembly.Git.BaseVersion.Minor won't change

### ISSUE THREAD

**Issue by cocakohler** [kzu/GitInfo#80]
I'm totally confused. I have a gitinfo.txt file within top-level of my repo.
No matter what i put into the file the ThisAssembly.Git.BaseVersion.Minor, ThisAssembly.Git.BaseVersion.Major, ThisAssembly.Git.BaseVersion.Patch keep the same.
Where does the definition of these variables come from?

The content of gitinfo.txt looks like this:
0.5.1

**Comment by kzu** [comment]
Please define `keep the same` (as in, what value are you getting, and what are you expecting). Also, attach a build log if possible, and provide some more context, like: is the file/repo a git repo? Is it committed? 

Thanks!

**Comment by kzu** [comment]
Closing from lack of activity.
