### ISSUE TITLE
Conflicts when using InternalsVisibleTo

### ISSUE THREAD

**Issue by drewnoakes** [kzu/GitInfo#84]
I want to add `GitInfo` to all projects in the solution via a `Directory.Build.targets` file.

Unfortunately we also use `InternalsVisibleTo` which results in errors due to duplicate `ThisAssembly` classes in `global::` namespace.

The apparent workaround is to define `$(ThisAssemblyNamespace)`, however as far as I can tell this must be done for _every_ project, and we must remember to add it to future projects.

Is there a way to pick up the default `$(RootNamespace)` value? I feel like this should drop the `ThisAssembly` type in the project's `RootNamespace` by default...

**Comment by kzu** [comment]
Just set ThisAssemblyNamespace=RootNamespace in the Directory.Build.targets?

**Comment by drewnoakes** [comment]
I ended up doing that and had some success, but got stuck on #85. Some generated files were not appearing with namespaces, and had GLOBALNAMESPACE defined, but I didn't get to a point that I was convinced there's a bug. #85 is a blocker for what I'm trying to do. If I can get past that, I'll come back to this. Closing for now. Thanks!
