### ISSUE TITLE
Emit assembly attributes

### ISSUE THREAD

**Issue by drewnoakes** [kzu/GitInfo#85]
We have a `CommonAssemblyInfo.cs` file that's included in all projects in the solution.

I wanted to add assembly attributes based that use `GitInfo` properties, as described in the README.

It seems this can't work in the case of `InternalsVisibleTo` because a shared file cannot import a unique namespace per consuming project.

Would it make sense to have a property that caused GitInfo to emit assembly attributes into the `.g.cs` file? I could them remove them from `CommonAssemblyInfo.cs`.

**Comment by kzu** [comment]
SDK-style projects already provide that. Or you can use `MSBuilder.AssemblyMetadata`. here's an example: https://github.com/moq/moq/blob/master/src/build/Version.targets

**Comment by drewnoakes** [comment]
It's a UI app so we're not using SDK projects yet.

Thanks for the example. I can see that it's possible, but it's more work than I'm willing to chew on right now. It feels like this should be something done once in this repo, and made easily available to all users via a simple property.

**Comment by kzu** [comment]
Understood, but this project does not intend to be overly prescriptive as to how you use those values. You can fairly easily do what you want with the things I mentioned. It's a package reference plus a couple MSBuild items on you targets.

**Comment by drewnoakes** [comment]
Thanks Daniel, I'll take another look.
