### ISSUE TITLE
Usefulness of Git.SemVer.Patch compared to Git.Commits?

### ISSUE THREAD

**Issue by DragonQ** [kzu/GitInfo#9]
If I make a git tag called "v1.0.1" and make a build, Git.SemVer.Patch is 1 and Git.Commits is 0. If I then make a commit and rebuild, Git.SemVer.Patch increases to 2 and Git.Commits increases to 1. What is the point of Git.SemVer.Patch automatically increasing with each commit if Git.Commits also does this? Doesn't this make the latter rather pointless and/or the former rather annoying?

I was hoping to have something like AssemblyFileVersion being Major.Minor.Patch and AssemblyInformationalVersion being Major.Minor.Patch.Commits, but that doesn't work with the current way Git.SemVer.Patch is calculated.

Would be interested to hear the author's thoughts on this. I have a feeling this is a git thing that can't be changed but maybe there's a workaround I haven't thought of.

EDIT: Never mind, I see that Git.BaseVersion.Patch can be used instead!

**Comment by kzu** [comment]
I'm thinking on actually splitting the NuGet into GitInfo (just the Git
stuff, no SemVer) and GitInfo.SemVer, and in that case it may make a bit
more sense. Also, you may not use SemVer at all, and use the Commits for a
Revision field instead, so using Patch would be weird in that case.

Dunno, maybe I'm just rationalizing an unnecessary duplication ;)

**Comment by kzu** [comment]
Yeah, the BaseVersion stuff is what comes from the fetched branch, tag or info file.

Glad it served your needs!
