### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by pedoc** [kzu/GitInfo#98]
hi,thank u work

i found Chinese garbled in the compiled result, as shown in the figure.
![image](https://user-images.githubusercontent.com/6604230/62631317-1cf17d80-b963-11e9-8b49-87931369928d.png)

how to fix it?

**Comment by kzu** [comment]
Please build with command line using `/bl` switch to generate a binary `.binlog` and open it using the [structured msbuild log viewer](msbuildlog.com). Examine the values received and processed by the `GitVersion` and `GitInfo` targets to see if they match what they should be. `GitInfo` basically calls out to `git log` and other git commands and then processes the output as text, so it should be mostly a pass-through from git output > msbuild properties > code files. Maybe there's an encoding issue?

**Comment by pedoc** [comment]
@kzu hi,sorry I am not an expert in msbuild, but I can provide a sample log:

[msbuild.zip](https://github.com/kzu/GitInfo/files/4450898/msbuild.zip)

**Comment by pedoc** [comment]
when execute `git rev-parse --show-toplevel` in cmd,output
![image](https://user-images.githubusercontent.com/6604230/78794818-cacb9500-79e6-11ea-9b91-e1b9d4d96432.png)
but,msbuild output is:
![image](https://user-images.githubusercontent.com/6604230/78794894-e3d44600-79e6-11ea-9c60-072a22a97293.png)

can you see garbled characters here, is this a bug of msbuild?

**Comment by pedoc** [comment]
ok,i found the reason and tried to solve this problem.
ref:https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019
please review PR,thanks
