### ISSUE TITLE
Can't Get BaseVersion.Patch+1

### ISSUE THREAD

**Issue by WalkerCodeRanger** [kzu/GitInfo#99]
I was really excited at first when I found your project, but due to the limits of constant expressions in C# I'm not able to get it to produce the versions that I need.

Specifically, if the base version is "v2.0.0 then I want "v2.0.1-dev.<_commits_>." The problem is in the patch number. I basically need `ThisAssembly.Git.BaseVersion.Minor + 1`. Of course, that can't be done because the minor version is a string and converting between strings and integers isn't possible in constant expressions.

Is there a way I can override the `$(GitSemVerPatch)` variable to be what I want?

In general, doesn't the limitation to constant expressions really make this approach not work well?

**Comment by kzu** [comment]
You can [inspect the targets](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L91-L92) and just place a new MSBuild target (typically in your `Directory.Build.targets`) in-between those to tweak the versions as you see fit. i.e.:

```xml
<Target Name="FixPatch" AfterTargets="GitVersion" BeforeTargets="GitThisAssembly">
  <PropertyGroup>
    <GitSemVerPatch Condition="'$(GitSemVerPatch)' == '0'">1</GitSemVerPatch>
  </PropertyGroup>
</Target>
```

You can do math or regexes or anything really, just like [the targets](https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L743-L752) do to calculate the semver values. 
What's important to realize is that all processing is done in *build*, so by the time the compiler sees the constants, whey are already all pre-calculated. This also means you can use those same values for anything else, not just code (i.e. append the version # to the output file name, such as in an MSI or a VSIX).
